from abc import ABC, abstractmethod
from typing import Any, Optional, Union, List
import functools as ft

import pyspark.sql.functions as F
from pyspark.sql import Column, DataFrame


class EnrichmentBase(ABC):
    """Base class for data enrichment.  It could be used for data enrichment using functions, or
    for example, by joining with another dataframe
    """

    __not_found_marker__ = "NotFound"

    def __init__(self, name: str):
        self._name = name

    @abstractmethod
    def enrich(self, df: DataFrame) -> DataFrame:
        """Performs enrichment of the given DataFrame

        :param df: DataFrame to enrich
        :return: enriched DataFrame
        """
        pass


class ColumnEnrichment(EnrichmentBase):
    """Class that enriches DataFrame with a single column
    """
    def __init__(self, name: str, alias: Optional[str] = None):
        super().__init__(name)
        self._alias = alias

    @abstractmethod
    def get_column(self, src: Optional[str] = None, alias: Optional[str] = None) -> Column:
        """Implementation need to provide this method by returning a Column object that
        performs enrichment of the data

        :return:
        """
        pass

    def enrich(self, df: DataFrame) -> DataFrame:
        """Enriches DataFrame by adding a new column with data generated by specified function.
        The main drawback of this implementation is that it won't expand data if column is struct
        :param df: DataFrame to enrich
        :return: new DataFrame with added column

        """
        cl = self.get_column()
        if self._alias:
            cl = cl.alias(self._alias)
        return df.select("*", cl)


class StaticValueEnrichment(ColumnEnrichment):
    """Class for enrichment of DataFrame with static value of any type supported by PySpark
    """
    def __init__(self, value: Any, alias: str):
        super().__init__("simple", alias=alias)
        self._value = value

    def get_column(self, src: Optional[str] = None, alias: Optional[str] = None) -> Column:
        cl = F.lit(self._value)
        if alias:
            cl = cl.alias(alias)
        elif self._alias:
            cl = cl.alias(self._alias)
        return cl


class DataFrameJoinEnrichment(EnrichmentBase):
    """Enriches DataFrame with information from another DataFrame by joining with it
    TODO: should it support multiple DataFrames?
    """
    def __init__(self, df: DataFrame,
                 condition: Union[str, List[str], Column, List[Column]],
                 join_type: Optional[str] = "left"):
        """
        Initializes the class
        :param df: DataFrame that will be used in right side of the join
        :param condition: join condition (string, list of strings, column or list of columns)
        :param join_type: join type. Default - left join
        """
        super().__init__("join")
        self._other_df = df
        self._join_type = join_type
        self._condition = condition

    @staticmethod
    def drop_duplicate_columns(ddf, sdf, columns):
        """Removes from `ddf` columns that are "duplicates" - usually it's used after a join to avoid ambiguity
        :param ddf: dataframe to remove columns from (usually it's a result of join)
        :param sdf: dataframe that is the source of the columns (another part of join)
        :param columns: names of the columns
        :return: modified `ddf` dataframe
        """
        def get_columns(df: DataFrame, columns: List[str]):
            """Returns a list of Column objects for given dataframe
            :param df: dataframe
            :param columns: list of column names
            :return: list of Column objects
            """
            return [df[col] for col in columns]

        return ft.reduce(DataFrame.drop, get_columns(sdf, columns), ddf)

    def enrich(self, df: DataFrame) -> DataFrame:
        """
        Enriches given DataFrame with information from another DataFrame
        :param df:
        :return:
        """
        joined = df.join(self._other_df, self._condition, self._join_type)
        # when we do equi-join, we don't get duplicate columns
        if self._condition is not None and (isinstance(self._condition, str) or
                                            (isinstance(self._condition, list) and
                                             len(self._condition) > 0 and
                                             isinstance(self._condition[0], str))):
            return joined
        # Drop columns with the same name
        cols = set(df.columns).intersection(set(self._other_df.columns))
        return DataFrameJoinEnrichment.drop_duplicate_columns(joined, self._other_df, cols)


class PandasFunctionEnrichmentBase(ColumnEnrichment):
    """Base class for all enrichment implementations based on the Pandas UDFs
    """
    def __init__(self, name: str, src_column_name_or_expr: str, dest_column_name: str):
        """
        Initializer
        :param name: name of implementation
        :param src_column_name_or_expr: name of the source column or SQL expression
        :param dest_column_name: name of the column in which data will be stored
        """
        super().__init__(name)
        self._src_column_name_or_expr = src_column_name_or_expr
        self._dest_column_name = dest_column_name

    @abstractmethod
    def create_pandas_udf_function(self):
        """Implementations need to override this function with a function that will return
         UDF/Pandas UDF that will perform actual enrichment
        """
        pass

    def get_column(self, src: Optional[str] = None, alias: Optional[str] = None) -> Column:
        if not src:
            src = self._src_column_name_or_expr
        if not alias:
            alias = self._dest_column_name
        return self.create_pandas_udf_function()(F.expr(src)).alias(alias)
