from pyspark.sql.types import *

raw_schema = (StructType()
    .add('_source', StringType(), True)
    .add('_type', StringType(), True)
    .add('_raw_record', StringType(), True)
    .add('_collection_ts', TimestampType(), True)
)

intel_schema = (
  StructType()
  .add('indicator', StringType(), True)
  .add('type', StringType(), True)
  .add('indicator_type', StringType(), True)
  .add('source', StringType(), True)
  .add('source_locator', StringType(), True)
  .add('tlp', StringType(), True)
  .add('tags', ArrayType(StringType(), True))
  .add('flags', MapType(StringType(), BooleanType(), True))
  .add('context', MapType(StringType(), StringType(), True))
  .add('date_first', DateType(), True)
  .add('date_last', DateType(), True)
  .add('ip_enrichment', 
     ArrayType(
          StructType()
            .add('ip', StringType(), True)
            .add('rdns', StringType(), True)
            .add('asn', IntegerType(), True)
            .add('asname', StringType(), True)
            .add('country', StringType(), True)
            .add('city', StringType(), True)
            .add('latitude', FloatType(), True)
            .add('longitude', FloatType(), True)
     )
  )
  .add('hash_enrichment', StructType()
       .add('md5', StringType(), True)
       .add('sha1', StringType(), True)
       .add('sha256', StringType(), True)
       .add('ssdeep', StringType(), True)
       .add('filetype', StringType(), True)
       .add('vt_detections', IntegerType(), True)
  )
)