# TODO: find schemas for all log types. Right now are missing: appstat, trsum, thsum, event, alarm,
#  mdm, extpcap, urlsum, gtp, gtpsum, panflex, extflex, sctpsum, analytics, action, scan, sam
__paloalto_log_schemas__ = {
    "authentication": "forwarder_id,log_time,log_source_id,log_type,sub_type,"
                      "config_version,time_generated,vsys,source_ip,user,"
                      "normalize_user,object,auth_policy,count_of_repeats,mfa_auth_id,"
                      "mfa_vendor,log_set,auth_server_profile,auth_description,client_type,"
                      "auth_event_name,auth_factor_num,sequence_no,action_flags,"
                      "dg_hier_level_1,dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,"
                      "vsys_name,log_source_name,vsys_id,auth_proto,rule_matched_uuid,"
                      "time_generated_high_res,source_device_category,source_device_profile,"
                      "source_device_model,source_device_vendor,source_device_os_family,"
                      "source_device_os_version,source_device_host,source_device_mac,"
                      "service_region,user_agent,session_id",
    "config": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
              "event_time,event_client_ip,vsys,event_name,admin_user,client,"
              "event_result,event_path,sequence_no,action_flags,dg_hier_level_1,"
              "dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,vsys_name,log_source_name,"
              "device_group,event_description,template,time_generated_high_res",
    "decryption": "forwarder_id,log_time,log_source_id,log_type,sub_type,"
                  "config_version,time_generated,source_ip,dest_ip,"
                  "nat_source,nat_dest,rule_matched,source_user,dest_user,app,"
                  "vsys,from_zone,to_zone,inbound_if,outbound_if,log_set,"
                  "time_received_mp,session_id,count_of_repeats,source_port,dest_port,"
                  "nat_source_port,nat_dest_port,flags,protocol,action,"
                  "tunnel,source_uuid,dest_uuid,rule_matched_uuid,"
                  "client_to_firewall,firewall_to_client,tls_version,"
                  "tls_keyxchange,tls_enc_algorithm,tls_auth,policy_name,"
                  "elliptic_curve,error_index,root_status,"
                  "chain_status,proxy_type,cert_serial,fingerprint,not_before,"
                  "not_after,certificate_version,certificate_size,cn_len,issuer_len,"
                  "root_cn_len,sni_len,cert_flags,cn,issuer_cn,root_cn,sni,error_message,"
                  "container_id,pod_namespace,pod_name,source_edl,dest_edl,"
                  "source_dynamic_address_group,dest_dynamic_address_group,"
                  "time_generated_high_res,source_device_category,source_device_profile,"
                  "source_device_model,source_device_vendor,source_device_os_family,"
                  "source_device_os_version,source_device_host,source_device_mac,"
                  "dest_device_category,dest_device_profile,dest_device_model,"
                  "dest_device_vendor,dest_device_os_family,dest_device_os_version,"
                  "dest_device_host,dest_device_mac,sequence_no,action_flags",
    "file": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
            "time_generated,source_ip,dest_ip,nat_source,"
            "nat_dest,rule_matched,source_user,dest_user,app,vsys,from_zone,"
            "to_zone,inbound_if,outbound_if,log_set,session_id,"
            "count_of_repeats,source_port,dest_port,nat_source_port,nat_dest_port,flags,"
            "protocol,action,file_name,file_id,url_category,"
            "vendor_severity,direction_of_attack,sequence_no,action_flags,"
            "source_location,dest_location,pcap_id,file_sha_256,report_id,dg_hier_level_1,"
            "dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,vsys_name,log_source_name,"
            "source_uuid,dest_uuid,tunnelid_imsi,monitor_tag_imei,parent_session_id,"
            "parent_start_time,tunnel,content_version,sig_flags,rule_matched_uuid,"
            "http2_connection,dynusergroup_name,xff_ip,source_device_category,"
            "source_device_profile,source_device_model,source_device_vendor,"
            "source_device_os_family,source_device_os_version,source_device_host,"
            "source_device_mac,dest_device_category,dest_device_profile,dest_device_model,"
            "dest_device_vendor,dest_device_os_family,dest_device_os_version,dest_device_host,"
            "dest_device_mac,container_id,pod_namespace,pod_name,source_edl,dest_edl,"
            "gp_host_id,endpoint_serial_number,domain_edl,source_dynamic_address_group,"
            "dest_dynamic_address_group,partial_hash,time_generated_high_res,"
            "reason_data_filtering,justification,nssai_network_slice_type",
    "globalprotect": "forwarder_id,log_time,log_source_id,log_type,sub_type,"
                     "config_version,time_generated,vsys,event_id,stage,"
                     "auth_method,tunnel,source_user,source_region,endpoint_device_name,"
                     "public_ip,public_ipv6,private_ip,"
                     "private_ipv6,host_id,endpoint_serial_number,endpoint_gp_version,"
                     "endpoint_os_type,endpoint_os_version,count_of_repeats,quarantine_reason,"
                     "connection_error,opaque,status,gpg_location,"
                     "login_duration,connect_method,connection_error_id,portal,sequence_no,"
                     "action_flags,time_generated_high_res,gateway_selection_type,"
                     "ssl_response_time,gateway_priority,attempted_gateways,gateway,"
                     "dg_hier_level_1,dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,"
                     "vsys_name,log_source_name,vsys_id",
    "hipmatch": "forwarder_id,log_time,log_source_id,log_type,sub_type,"
                "config_version,time_generated,source_user,vsys,endpoint_device_name,"
                "endpoint_os_type,source_ip,hip_match_name,count_of_repeats,"
                "hip_match_type,sequence_no,action_flags,dg_hier_level_1,"
                "dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,vsys_name,log_source_name,"
                "vsys_id,source_ip_v6,host_id,endpoint_serial_number,"
                "source_device_category,source_device_profile,source_device_model,"
                "source_device_vendor,source_device_os_family,source_device_os_version,"
                "source_device_mac,source_device_host,source,timestamp_device_identification,"
                "time_generated_high_res",
    "iptag": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
             "time_generated,vsys,source_ip,tag_name,event_id,"
             "count_of_repeats,mapping_timeout,mapping_data_source_name,"
             "mapping_data_source_type,mapping_data_source_sub_type,sequence_no,"
             "action_flags,dg_hier_level_1,dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,"
             "vsys_name,log_source_name,vsys_id,ip_subnet_range,time_generated_high_res",
    "sctp": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
            "time_generated,source_ip,dest_ip,nat_source,"
            "nat_dest,rule_matched,source_user,dest_user,app,vsys,from_zone,"
            "to_zone,inbound_if,outbound_if,log_set,session_id,"
            "count_of_repeats,source_port,dest_port,nat_source_port,nat_dest_port,flags,"
            "protocol,action,dg_hier_level_1,dg_hier_level_2,dg_hier_level_3,"
            "dg_hier_level_4,vsys_name,log_source_name,sequence_no,action_flags,ep_assoc_id,"
            "payload_protocol_id,vendor_severity,sctp_chunk_type,event_type,"
            "event_code,verification_tag_1,verification_tag_2,sctp_cause_code,diam_app_id,"
            "diam_cmd_code,diam_avp_code,stream_id,association_end_reason,map_op_code,"
            "sccp_calling_ssn,sccp_calling_gt,sctp_filter,chunks_total,chunks_sent,"
            "chunks_received,packets_total,packets_sent,packets_received,rule_matched_uuid,"
            "container_id,pod_namespace,pod_name,source_edl,dest_edl,"
            "source_dynamic_address_group,dest_dynamic_address_group,time_generated_high_res",
    "system": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
              "event_time,vsys,event_name,event_component,event_component_id,"
              "vendor_severity,event_description,sequence_no,action_flags,dg_hier_level_1,"
              "dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,vsys_name,log_source_name,"
              "device_group,template,time_generated_high_res",
    "threat": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
              "time_generated,source_ip,dest_ip,nat_source,"
              "nat_dest,rule_matched,source_user,dest_user,app,vsys,from_zone,"
              "to_zone,inbound_if,outbound_if,log_set,session_id,"
              "count_of_repeats,source_port,dest_port,nat_source_port,nat_dest_port,flags,"
              "protocol,action,file_name,threat_id,url_category,"
              "vendor_severity,direction_of_attack,sequence_no,action_flags,"
              "source_location,dest_location,pcap_id,file_sha_256,cloud,url_idx,file_type,"
              "sender_of_virus,subject_of_email,recipient_of_virus,report_id,dg_hier_level_1,"
              "dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,vsys_name,log_source_name,"
              "source_uuid,dest_uuid,tunnelid_imsi,monitor_tag_imei,parent_session_id,"
              "parent_start_time,tunnel,threat_category,content_version,"
              "sig_flags,rule_matched_uuid,http2_connection,dynusergroup_name,xff_ip,"
              "source_device_category,source_device_profile,source_device_model,"
              "source_device_vendor,source_device_os_family,source_device_os_version,"
              "source_device_host,source_device_mac,dest_device_category,dest_device_profile,"
              "dest_device_model,dest_device_vendor,dest_device_os_family,"
              "dest_device_os_version,dest_device_host,dest_device_mac,container_id,"
              "pod_namespace,pod_name,source_edl,dest_edl,host_id,endpoint_serial_number,"
              "domain_edl,source_dynamic_address_group,dest_dynamic_address_group,"
              "partial_hash,time_generated_high_res,nssai_network_slice_type ",
    "traffic": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
               "time_generated,source_ip,dest_ip,nat_source,"
               "nat_dest,rule_matched,source_user,dest_user,app,vsys,from_zone,"
               "to_zone,inbound_if,outbound_if,log_set, future_use1, session_id,"
               "count_of_repeats,source_port,dest_port,nat_source_port,nat_dest_port,flags,"
               "protocol,action,bytes_total,bytes_sent,bytes_received,"
               "packets_total,session_start_time,total_time_elapsed,url_category,future_use2,"
               "sequence_no,action_flags,source_location,dest_location,future_use3,packets_sent,"
               "packets_received,session_end_reason,dg_hier_level_1,dg_hier_level_2,"
               "dg_hier_level_3,dg_hier_level_4,vsys_name,log_source_name,"
               "action_source,source_uuid,dest_uuid,tunnelid_imsi,monitor_tag_imei,"
               "parent_session_id,parent_start_time,tunnel,ep_assoc_id,chunks_total,"
               "chunks_sent,chunks_received,rule_matched_uuid,http2_connection,"
               "link_change_count,policy_id,link_switches,sdwan_cluster,sdwan_device_type,"
               "sdwan_cluster_type,sdwan_site,dynusergroup_name,xff_ip,"
               "source_device_category,source_device_profile,source_device_model,"
               "source_device_vendor,source_device_os_family,source_device_os_version,"
               "source_device_host,source_device_mac,dest_device_category,dest_device_profile,"
               "dest_device_model,dest_device_vendor,dest_device_os_family,"
               "dest_device_os_version,dest_device_host,dest_device_mac,container_id,"
               "pod_namespace,pod_name,source_edl,dest_edl,host_id,endpoint_serial_number,"
               "source_dynamic_address_group,dest_dynamic_address_group,ha_session_owner,"
               "time_generated_high_res,nssai_network_slice_type,"
               "nssai_network_slice_differentiator,"
               "app_subcategory,app_category,app_tech,app_risk,app_character,app_container,"
               "tunneled_app,app_saas,app_sanctioned_state,offloaded",
    "tunnel": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
              "time_generated,source_ip,dest_ip,nat_source,"
              "nat_dest,rule_matched,source_user,dest_user,app,vsys,from_zone,"
              "to_zone,inbound_if,outbound_if,log_set,session_id,"
              "count_of_repeats,source_port,dest_port,nat_source_port,nat_dest_port,flags,"
              "protocol,action,tunnel_event_type,mobile_subscriber_isdn,"
              "access_point_name,radio_access_technology,tunnel_message_type,mobile_ip,"
              "tunnel_endpoint_id_1,tunnel_endpoint_id_2,tunnel_interface,tunnel_cause_code,"
              "vendor_severity,mobile_country_code,mobile_network_code,"
              "mobile_area_code,mobile_base_station_code,tunnel_event_code,sequence_no,"
              "action_flags,source_location,dest_location,dg_hier_level_1,dg_hier_level_2,"
              "dg_hier_level_3,dg_hier_level_4,vsys_name,log_source_name,tunnelid_imsi,"
              "monitor_tag_imei,parent_session_id,parent_start_time,tunnel,"
              "bytes_total,bytes_sent,bytes_received,packets_total,packets_sent,"
              "packets_received,packets_dropped_max_encap,packets_dropped_ukn_proto,"
              "packets_dropped_strict_check,packets_dropped_tunnel_frag,"
              "tunnel_sessions_created,tunnel_sessions_closed,session_end_reason,"
              "action_source,session_start_time,total_time_elapsed,"
              "tunnel_inspection_rule,tunnel_remote_user_ip,tunnel_remote_imsi_id,"
              "rule_matched_uuid,dynusergroup_name,container_id,pod_namespace,pod_name,"
              "source_edl,dest_edl,source_dynamic_address_group,dest_dynamic_address_group,"
              "time_generated_high_res,nssai_network_slice_differentiator,"
              "nssai_network_slice_type,pdu_session_id",
    "url": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
           "time_generated,source_ip,dest_ip,nat_source,nat_dest,"
           "rule_matched,source_user,dest_user,app,vsys,from_zone,to_zone,"
           "inbound_if,outbound_if,log_set,session_id,count_of_repeats,"
           "source_port,dest_port,nat_source_port,nat_dest_port,flags,protocol,"
           "action,uri,url_category,vendor_severity,"
           "direction_of_attack,sequence_no,action_flags,source_location,"
           "dest_location,content_type,pcap_id,url_idx,user_agent,xff,referer,"
           "dg_hier_level_1,dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,vsys_name,"
           "log_source_name,source_uuid,dest_uuid,http_method,tunnelid_imsi,"
           "monitor_tag_imei,parent_session_id,parent_start_time,tunnel,"
           "inline_ml_verdict,content_version,sig_flags,http_headers,"
           "url_category_list,rule_matched_uuid,http2_connection,dynusergroup_name,"
           "xff_ip,source_device_category,source_device_profile,source_device_model,"
           "source_device_vendor,source_device_os_family,source_device_os_version,"
           "source_device_host,source_device_mac,dest_device_category,dest_device_profile,"
           "dest_device_model,dest_device_vendor,dest_device_os_family,dest_device_os_version,"
           "dest_device_host,dest_device_mac,container_id,pod_namespace,pod_name,source_edl,"
           "dest_edl,gp_host_id,endpoint_serial_number,domain_edl,"
           "source_dynamic_address_group,dest_dynamic_address_group,partial_hash,"
           "time_generated_high_res,nssai_network_slice_type",
    "userid": "forwarder_id,log_time,log_source_id,log_type,sub_type,config_version,"
              "time_generated,vsys,source_ip,user,mapping_data_source_name,event_id,"
              "count_of_repeats,mapping_timeout,source_port,dest_port,"
              "mapping_data_source,mapping_data_source_type,sequence_no,"
              "action_flags,dg_hier_level_1,dg_hier_level_2,dg_hier_level_3,dg_hier_level_4,"
              "vsys_name,log_source_name,vsys_id,mfa_factor_type,auth_completion_time,"
              "auth_factor_num,ug_flags,user_identified_by_source_as,tag_name,"
              "time_generated_high_res",
    # "": "forwarder_id,",
}