# generated by datamodel-codegen:
#   filename:  enrichments.yaml
#   timestamp: 2023-07-04T12:07:49+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ValidationError, RootModel

from pathlib import Path
import yaml
from databricks.sirens.logging import get_logger

logger = get_logger(__name__)


class Filters(BaseModel):
    prefilter: Optional[str] = None
    postfilter: Optional[str] = None
    output_columns: Optional[List[str]] = None


class ModelItem(BaseModel):
    name: str
    join_type: Optional[str] = None
    broadcast: Optional[bool] = None
    table: Optional[str] = None
    file: Optional[str] = None
    source_column: str
    target_column: Optional[str] = None
    join_expr: Optional[str] = None
    filters: Optional[Filters] = None


Model = RootModel[List[ModelItem]]


def start(self, file):
    self.file = file
    path = Path(self.file)

    try:
        with open(path, 'r') as fp:
            con = yaml.safe_load(fp)
    except yaml.YAMLError as exc:
        print("Error while parsing YAML file:")
        if hasattr(exc, 'problem_mark'):
            if exc.context is not None:
                print(f"  parser says\n{str(exc.problem_mark)}")
                print(f"  {str(exc.problem)} {str(exc.context)}")
                print("Please correct data and retry.")
            else:
                print(f"  parser says\n{str(exc.problem_mark)}")
                print(f"{str(exc.problem)}Please correct data and retry")
                print("Please correct data and retry.")
                return 1
        else:
            print("Something went wrong while parsing yaml file")
            return 1

    try:
        Model.model_validate(con)
        return 0

    except ValidationError as exc:
        print(exc)
        return 1