from databricks.sirens.internal.secrets import SecretsManager

def test_substitute_secrets_no_subs():
    d = dict({'input': {'source': 'apache', 'sourcetype': 'access_combined', 'parser': 'apache_access_combined', 'rawPath': 'LocalPath://apache/access_combined/samples/', 'connector': {'name': 'autoloader', 'options': {'cloudFiles.format': 'text', 'cloudFiles.includeExistingFiles': True}}, 'streamType': 'streaming'}, 'databaseName': 'sirens', 'transforms': {'bronze': {'enrichments': ['iana_ports'], 'meta': {'host_column': 'value', 'host_regex': '^(?<host>[^ ]*)', 'timestamp_column': 'value', 'timestamp_regex': '^(?<host>[^ ]*) [^ ]* ([^ ]*) \\[(?<time>[^\\]]*)\\]', 'timestamp_format': 'dd/MMM/yyyy:HH:mm:ss Z'}}, 'silver': {'event_type': [{'target_table': 'web', 'filter': '_sourcetype == "access_combined"', 'enrichments': ['iana_ports'], 'fields': [{'event_message': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_message_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_schema_version': {'action': 'add', 'type': 'literal', 'value': 1.0}}, {'event_schema_file': {'action': 'add', 'type': 'literal', 'value': 'access_log'}}, {'event_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'_sourcetype': {'action': 'rename', 'value': '_sourcetype'}}, {'_event_date': {'action': 'rename', 'value': '_event_date'}}, {'_event_time': {'action': 'rename', 'value': '_event_time'}}, {'src_hostname': {'action': 'alias', 'value': 'host'}}, {'user_name': {'action': 'alias', 'value': 'user'}}, {'http_method': {'action': 'alias', 'value': 'method'}}, {'url_path': {'action': 'alias', 'value': 'path'}}, {'http_status_code': {'action': 'alias', 'value': 'code'}}, {'http_response_body_bytes': {'action': 'alias', 'value': 'size'}}, {'http_referrer_original': {'action': 'alias', 'value': 'referer'}}, {'http_user_agent': {'action': 'alias', 'value': 'agent'}}]}]}, 'gold': {'aggregate': ['apache_web_stats_by_hour']}}, 'config': {'version': 1.0, 'updated': '20/6/2022', 'author': 'Derek King', 'description': 'Process apache common log format (access_combined) logs'}})
    result = SecretsManager().substitute_secrets(d)
    assert result == d

def test_substitute_secrets_with_subs(mocker):
    mocker.patch("databricks.sirens.internal.secrets.SecretsManager.get_secret", return_value="[REDACTED]")
    d = dict({'input': {'source': 'apache', 'sourcetype': 'access_combined', 'parser': 'apache_access_combined', 'rawPath': 'LocalPath://apache/access_combined/samples/', 'connector': {'name': 'autoloader', 'options': {'cloudFiles.format': 'text', 'cloudFiles.awsSecret': '{{secrets/scope/key}}'}}, 'streamType': 'streaming'}, 'databaseName': 'sirens', 'transforms': {'bronze': {'enrichments': ['iana_ports'], 'meta': {'host_column': 'value', 'host_regex': '^(?<host>[^ ]*)', 'timestamp_column': 'value', 'timestamp_regex': '^(?<host>[^ ]*) [^ ]* ([^ ]*) \\[(?<time>[^\\]]*)\\]', 'timestamp_format': 'dd/MMM/yyyy:HH:mm:ss Z'}}, 'silver': {'event_type': [{'target_table': 'web', 'filter': '_sourcetype == "access_combined"', 'enrichments': ['iana_ports'], 'fields': [{'event_message': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_message_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_schema_version': {'action': 'add', 'type': 'literal', 'value': 1.0}}, {'event_schema_file': {'action': 'add', 'type': 'literal', 'value': 'access_log'}}, {'event_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'_sourcetype': {'action': 'rename', 'value': '_sourcetype'}}, {'_event_date': {'action': 'rename', 'value': '_event_date'}}, {'_event_time': {'action': 'rename', 'value': '_event_time'}}, {'src_hostname': {'action': 'alias', 'value': 'host'}}, {'user_name': {'action': 'alias', 'value': 'user'}}, {'http_method': {'action': 'alias', 'value': 'method'}}, {'url_path': {'action': 'alias', 'value': 'path'}}, {'http_status_code': {'action': 'alias', 'value': 'code'}}, {'http_response_body_bytes': {'action': 'alias', 'value': 'size'}}, {'http_referrer_original': {'action': 'alias', 'value': 'referer'}}, {'http_user_agent': {'action': 'alias', 'value': 'agent'}}]}]}, 'gold': {'aggregate': ['apache_web_stats_by_hour']}}, 'config': {'version': 1.0, 'updated': '20/6/2022', 'author': 'Derek King', 'description': 'Process apache common log format (access_combined) logs'}})
    result = SecretsManager().substitute_secrets(d)
    assert isinstance(result, dict)
    assert result.get("input").get("connector").get("options").get("cloudFiles.awsSecret") == "[REDACTED]"

def test_substitute_secrets_invalid_input(mocker):
    d = ["a list", "not_valid_input"]
    result = SecretsManager().substitute_secrets(d)
    assert result == d

def test_substitute_secrets_with_secret_in_list_item(mocker):
    mocker.patch("databricks.sirens.internal.secrets.SecretsManager.get_secret", return_value="[REDACTED]")
    d = dict({'input': {'source': 'apache', 'sourcetype': 'access_combined', 'parser': 'apache_access_combined', 'rawPath': 'LocalPath://apache/access_combined/samples/', 'connector': {'name': 'autoloader', 'options': {'cloudFiles.format': 'text', 'cloudFiles.awsSecret': '123456789'}}, 'streamType': 'streaming'}, 'databaseName': 'sirens', 'transforms': {'bronze': {'enrichments': ['{{secrets/scope/key}}'], 'meta': {'host_column': 'value', 'host_regex': '^(?<host>[^ ]*)', 'timestamp_column': 'value', 'timestamp_regex': '^(?<host>[^ ]*) [^ ]* ([^ ]*) \\[(?<time>[^\\]]*)\\]', 'timestamp_format': 'dd/MMM/yyyy:HH:mm:ss Z'}}, 'silver': {'event_type': [{'target_table': 'web', 'filter': '_sourcetype == "access_combined"', 'enrichments': ['iana_ports'], 'fields': [{'event_message': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_message_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_schema_version': {'action': 'add', 'type': 'literal', 'value': 1.0}}, {'event_schema_file': {'action': 'add', 'type': 'literal', 'value': 'access_log'}}, {'event_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'_sourcetype': {'action': 'rename', 'value': '_sourcetype'}}, {'_event_date': {'action': 'rename', 'value': '_event_date'}}, {'_event_time': {'action': 'rename', 'value': '_event_time'}}, {'src_hostname': {'action': 'alias', 'value': 'host'}}, {'user_name': {'action': 'alias', 'value': 'user'}}, {'http_method': {'action': 'alias', 'value': 'method'}}, {'url_path': {'action': 'alias', 'value': 'path'}}, {'http_status_code': {'action': 'alias', 'value': 'code'}}, {'http_response_body_bytes': {'action': 'alias', 'value': 'size'}}, {'http_referrer_original': {'action': 'alias', 'value': 'referer'}}, {'http_user_agent': {'action': 'alias', 'value': 'agent'}}]}]}, 'gold': {'aggregate': ['apache_web_stats_by_hour']}}, 'config': {'version': 1.0, 'updated': '20/6/2022', 'author': 'Derek King', 'description': 'Process apache common log format (access_combined) logs'}})
    result = SecretsManager().substitute_secrets(d)
    assert isinstance(result, dict)
    assert result.get("transforms").get("bronze").get("enrichments")[0] == '[REDACTED]'

def test_w_unexpected_type(mocker):
    mocker.patch("databricks.sirens.internal.secrets.SecretsManager.get_secret", return_value="[REDACTED]")
    d = dict({'input': {'source': 'apache', 'sourcetype': 'access_combined', 'parser': 'apache_access_combined', 'rawPath': 'LocalPath://apache/access_combined/samples/', 'connector': {'name': 'autoloader', 'options': {'cloudFiles.format': 'text', 'cloudFiles.awsSecret': '<INVALID_TYPE:scope:key>'}}, 'streamType': 'streaming'}, 'databaseName': 'sirens', 'transforms': {'bronze': {'enrichments': ['iana_ports'], 'meta': {'host_column': 'value', 'host_regex': '^(?<host>[^ ]*)', 'timestamp_column': 'value', 'timestamp_regex': '^(?<host>[^ ]*) [^ ]* ([^ ]*) \\[(?<time>[^\\]]*)\\]', 'timestamp_format': 'dd/MMM/yyyy:HH:mm:ss Z'}}, 'silver': {'event_type': [{'target_table': 'web', 'filter': '_sourcetype == "access_combined"', 'enrichments': ['iana_ports'], 'fields': [{'event_message': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_message_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_schema_version': {'action': 'add', 'type': 'literal', 'value': 1.0}}, {'event_schema_file': {'action': 'add', 'type': 'literal', 'value': 'access_log'}}, {'event_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'_sourcetype': {'action': 'rename', 'value': '_sourcetype'}}, {'_event_date': {'action': 'rename', 'value': '_event_date'}}, {'_event_time': {'action': 'rename', 'value': '_event_time'}}, {'src_hostname': {'action': 'alias', 'value': 'host'}}, {'user_name': {'action': 'alias', 'value': 'user'}}, {'http_method': {'action': 'alias', 'value': 'method'}}, {'url_path': {'action': 'alias', 'value': 'path'}}, {'http_status_code': {'action': 'alias', 'value': 'code'}}, {'http_response_body_bytes': {'action': 'alias', 'value': 'size'}}, {'http_referrer_original': {'action': 'alias', 'value': 'referer'}}, {'http_user_agent': {'action': 'alias', 'value': 'agent'}}]}]}, 'gold': {'aggregate': ['apache_web_stats_by_hour']}}, 'config': {'version': 1.0, 'updated': '20/6/2022', 'author': 'Derek King', 'description': 'Process apache common log format (access_combined) logs'}})
    result = SecretsManager().substitute_secrets(d)
    assert d == result

def test_substitute_secrets_w_invalid_input(mocker):
    mocker.patch("databricks.sirens.internal.secrets.SecretsManager.get_secret", return_value="[REDACTED]")
    d = dict({'input': {'source': 'apache', 'sourcetype': 'access_combined', 'parser': 'apache_access_combined', 'rawPath': 'LocalPath://apache/access_combined/samples/', 'connector': {'name': 'autoloader', 'options': {'cloudFiles.format': 'text', 'cloudFiles.awsSecret': '{{secrets-scope/key}}'}}, 'streamType': 'streaming'}, 'databaseName': 'sirens', 'transforms': {'bronze': {'enrichments': ['iana_ports'], 'meta': {'host_column': 'value', 'host_regex': '^(?<host>[^ ]*)', 'timestamp_column': 'value', 'timestamp_regex': '^(?<host>[^ ]*) [^ ]* ([^ ]*) \\[(?<time>[^\\]]*)\\]', 'timestamp_format': 'dd/MMM/yyyy:HH:mm:ss Z'}}, 'silver': {'event_type': [{'target_table': 'web', 'filter': '_sourcetype == "access_combined"', 'enrichments': ['iana_ports'], 'fields': [{'event_message': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_message_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'event_schema_version': {'action': 'add', 'type': 'literal', 'value': 1.0}}, {'event_schema_file': {'action': 'add', 'type': 'literal', 'value': 'access_log'}}, {'event_result': {'action': 'add', 'type': 'literal', 'value': 'success'}}, {'_sourcetype': {'action': 'rename', 'value': '_sourcetype'}}, {'_event_date': {'action': 'rename', 'value': '_event_date'}}, {'_event_time': {'action': 'rename', 'value': '_event_time'}}, {'src_hostname': {'action': 'alias', 'value': 'host'}}, {'user_name': {'action': 'alias', 'value': 'user'}}, {'http_method': {'action': 'alias', 'value': 'method'}}, {'url_path': {'action': 'alias', 'value': 'path'}}, {'http_status_code': {'action': 'alias', 'value': 'code'}}, {'http_response_body_bytes': {'action': 'alias', 'value': 'size'}}, {'http_referrer_original': {'action': 'alias', 'value': 'referer'}}, {'http_user_agent': {'action': 'alias', 'value': 'agent'}}]}]}, 'gold': {'aggregate': ['apache_web_stats_by_hour']}}, 'config': {'version': 1.0, 'updated': '20/6/2022', 'author': 'Derek King', 'description': 'Process apache common log format (access_combined) logs'}})
    result = SecretsManager().substitute_secrets(d)
    assert d == result